version: '3.8'
services:
  db:
    image: 'postgres:13'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: almoxarifado_kine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
